### PR TITLE
Added pypi badge + Releases to badges list

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
Work includes:
 - Adding the PyPi badge for the release version
 - Adds a "Release" section to the badges for PyPi version and Zenodo DOI badge

To test:
 - [Go to branch](https://github.com/ChalkLab/SciDataLib/tree/add-pypi-badge) and look at README. Ensure badge layout looks okay

### CODE REVIEW

**Comment by marshallmcdonnell** [comment]
@stuchalk is there anything you would like me to change in this PR?
I am happy to do so directly on this branch, if you like.

**Comment by stuchalk** [comment]
Looks good to me.

**Review by stuchalk — APPROVED** [review]
Looks good to me...

**Comment by marshallmcdonnell** [comment]
Thanks! :+1:

**Pull request merged**
