### PR TITLE
Adds jcamp reader to scidatalib.io.jcamp

### PR DESCRIPTION
**Pull request by marshallmcdonnell**
Partially closes issue #48 

Work includes:
 - initial parsing code for JCAMP file format reading (no writing yet to address #49) into `SciData` object
 - Testing of the new `scidatalib.io.jcamp` module. Tests that are missing (will work on them, current coverage of module is ~91%~ 98%):
   - ~`_read_get_aspects_section`~
   - ~`_read_get_facets_section`~
   - `_read_get_dataseries_subsection` (needs dataseries method added to SciData class)
 - Adds multiple test JCAMP data files
 - Adding [`numpy`](https://numpy.org/) as a dependency to the project

Work still needed to close out issue #48 is to add the ability to include the `dataseries`.
Will do once we finish up #43

### CODE REVIEW

**Comment by stuchalk** [comment]
Just for clarification the code you have for jcamp was developed in house right.  There is also this project that might be something to look at ... https://github.com/nzhagen/jcamp

**Comment by marshallmcdonnell** [comment]
@stuchalk So I "used" that project you mention but heavily refactored the code (split it up from being a "mega-function", tried to apply  "don't repeat yourself" to certain parts", added additional testing, general re-writing, etc.)

I fee like I have done what is needed based on the original licensing (MIT, like ours) to reproduce the code here as our own copy:
https://github.com/ChalkLab/SciDataLib/blob/48-add-jcamp-reader/scidatalib/io/jcamp.py#L1-L29

My biggest concern with bringing the package in as a dependency is the [lag in new releases](https://github.com/nzhagen/jcamp/issues/23). The current version looks to have updates as of 2020 but the [last PyPi release was 2017](https://pypi.org/project/jcamp/#history). Instead, I thought it best to "control" the few hundred lines of code that this package provides as a modified copy we can maintain. 

Thoughts?

**Comment by stuchalk** [comment]
Yes, I remember now, you said that in our last call.  So, I agree with the idea of using the code and not relying on releases from the author, although we clearly should identify the original developer.  Maybe we should get the code as a fork? Not sure that will work...

**Comment by marshallmcdonnell** [comment]
To clearly identify the original author, I have the following lines in the file:
> Original author for JCAMP reader code:
>    Nathan Hagen, 2013, https://github.com/nzhagen/jcamp

That info can be found here in the source code:
https://github.com/ChalkLab/SciDataLib/blob/48-add-jcamp-reader/scidatalib/io/jcamp.py#L1-L29

I don't know if a fork would help us if we want to have it as a "dependency" we pull in since we would need to publish a PyPi package.
Yet, the original author already has published a package, which only leads to confusion in my opinion.

**Comment by stuchalk** [comment]
OK, sounds good.

**Review by stuchalk — APPROVED** [review]
Looks good...

**Comment by marshallmcdonnell** [comment]
@stuchalk thank you!
I'll probably add a few tests (facets and aspects) that I am working on right now.
If they give a "green" for CI, I'll go ahead and merge after that since it really won't change the source code of SciDataLib

Thanks for looking this over! :+1:

**Pull request merged**
